# Site settings
title: Commit Check Documentation
description: A powerful tool for enforcing commit metadata standards
url: "https://commit-check.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Sass configuration
sass:
  style: compressed

# Social links
github_username: commit-check

# Exclude files
exclude:
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfile
  - gemfile.lock
  - vendor/
  - README.md