site_name: "commit-check"
site_description: "Documentation for the commit-check organization."
site_url: "https://commit-check.github.io/"
repo_url: https://github.com/commit-check
repo_name: "commit-check"
copyright: "© 2021-2025, commit-check"

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  # - Blog:
  #     - blog/index.md
exclude_docs: |
  blog/**

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - navigation.sections
  favicon: static/favicon.ico
  icon:
    logo: material/git
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to system preference


markdown_extensions:
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/commit-check
  # analytics:
  #   provider: google
  #   property: G-JKH4SXC7HC
